# Dependencies
markdown:         redcarpet
hightligther:         true

# Permalinks
permalink:        pretty

# Setup
title:            Patente moi ça
tagline:          'Peux-tu me patenter ça?'
description:      'patenter<em>/pa.tɑ̃.te/</em>:<br>Inventer, fabriquer<br>To invent, to make.'
url:              http://patentemoi.ca
baseurl:          /

author:
  name:           'Benoit Caron'
  url:            https://twitter.com/bencaron

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bencaron/
